config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  resources :events, except: [:index] do
    resources :tickets, only: [:new, :create, :destroy]
  end

  resources :users, only: [:destroy] do
    get :retire
  end

  # Catch paths that don't match any paths above
  # (and store them as 'params[:path]').
  match '*path' => 'application#error404', via: :all
end

app/models/event.rb
class Event < ActiveRecord::Base
  mount_uploader :event_image, EventImageUploader

  belongs_to :owner, class_name: 'User'
  has_many :tickets, dependent: :destroy

  validates :name,
    presence: true,
    length: { maximum: 50 }

  validates :place,
    presence: true,
    length: { maximum: 100 }

  validates :start_time,
    presence: true

  validates :end_time,
    presence: true

  validates :content,
    presence: true,
    length: { maximum: 2000 }

  validate :start_time_should_be_before_end_time

  def created_by?(user)
    user && owner_id == user.id
  end

  def ticket_of(user)
    return unless user
    tickets.find do |t|
      t.user_id == user.id
    end
  end

  private

  def start_time_should_be_before_end_time
    return unless start_time && end_time

    if start_time > end_time
      errors.add :start_time, 'は終了時間よりも前に設定してください'
    end
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  validates :comment,
    allow_blank: true,
    length: { maximum: 30 }
end

app/models/user.rb
class User < ActiveRecord::Base
  before_destroy :check_all_events_finished

  has_many :created_events,
    class_name: :Event,
    foreign_key: :owner_id,
    dependent: :nullify

  has_many :tickets,
    dependent: :nullify

  has_many :participating_events,
    through: :tickets,
    source: :event

  def self.find_or_create_from_auth_hash(auth_hash)
    provider = auth_hash[:provider]
    uid = auth_hash[:uid]
    nickname = auth_hash[:info][:nickname]
    image_url = auth_hash[:info][:image]

    User.find_or_create_by(provider: provider, uid: uid) do |user|
      user.nickname = nickname
      user.image_url = image_url
    end
  end

  private

  def check_all_events_finished
    now = Time.zone.now

    if created_events.where('? < end_time', now).exists?
      errors[:base] << '公開中の未終了イベントが存在します'
    end

    if participating_events.where('? < end_time', now).exists?
      errors[:base] << '未終了の参加イベントが存在します'
    end

    errors.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Register as helper methods to use them in views.
  helper_method :logged_in?, :current_user

  unless Rails.env.development?
    rescue_from StandardError, with: :error500
    rescue_from ActiveRecord::RecordNotFound, with: :error404
  end

  def error404
    render 'error404', status: 404, formats: [:html]
  end

  def error500(e)
    logger.error [e, *e.backtrace].join('\n')
    render 'error500', status: 500, formats: [:html]
  end

  private

  # Return the current logged in user.
  def current_user
    return unless logged_in?
    @current_user ||= User.find(session[:user_id])
  end

  # Redirect to the home page when there is no logged in user.
  # It should be used as 'before_action'.
  def authenticate
    return if logged_in?
    redirect_to root_path, alert: 'ログインしてください'
  end

  # Return whether or not the user is logged in.
  def logged_in?
    !! session[:user_id]
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate, except: :show

  def new
    # Instanciate a new event.
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event, notice: '作成しました'
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    @new_ticket = @event.tickets.build
    @my_ticket = current_user && @event.ticket_of(current_user)

    # The `includes` method loads all relavent users.
    @tickets = @event.tickets.includes(:user).order(:created_at)
  end

  def edit
    @event = current_users_event(params[:id])
  end

  def update
    @event = current_users_event(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    @event = current_users_event(params[:id])
    @event.destroy!
    redirect_to root_path, notice: '削除しました'
  end

  private

  def current_users_event(id)
    current_user.created_events.find(id)
  end

  def event_params
    params.require(:event).permit(
      :name, :place, :content, :start_time, :end_time,
      :event_image, :remove_event_image
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth_hash = request.env['omniauth.auth']
    user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = user.id
    redirect_to root_path, notice: 'ログインしました'
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました'
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate

  def new
    raise ActionController::RoutingError,
      'ログイン状態で TicketsController#show にアクセス'
  end

  def create
    ticket = current_user.tickets.build do |t|
      t.event_id = params[:event_id]
      t.comment = params[:ticket][:comment]
    end

    if ticket.save
      flash[:notice] = 'このイベントに参加表明しました'
      head :created
    else
      render json: {
        messages: ticket.errors.full_messages
      }, status: 422
    end
  end

  def destroy
    ticket = current_user.tickets.find(params[:id])
    ticket.destroy!

    event_id = params[:event_id]
    redirect_to event_path(event_id), notice: '参加をキャンセルしました'
  end

  private

  def ticket_params
    params.permit(:event_id, :comment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate

  def retire
  end

  def destroy
    # current_user.check_all_events_finished
    # ret = current_user.destroy
    # binding.pry
    # raise StandardError if ret
    # render :retire
    if current_user.destroy
      reset_session
      redirect_to root_path, notice: '退会しました'
    else
      render :retire
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  PER = 10

  def index
    # Select events not held yet.
    @events = Event.
      page(params[:page]).per(PER).
      where('start_time > ?', Time.zone.now).order(:start_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Create an URL to a twitter account.
  def url_for_twitter(user)
    user && "https://twitter.com/#{user.nickname}"
  end
end

app/helpers/events_helper.rb
module EventsHelper

  def format_datetime(time)
    return '' unless time
    time.strftime('%Y/%m/%d %H:%M')
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/error404.html.erb
<div class="page-header">
  <h1>ご指定になったページは存在しません</h1>
</div>

<%= link_to '戻る', root_path %>

app/views/application/error500.html.erb
<div class="page-header">
  <h1>エラーが発生しました</h1>
</div>

<%= link_to '戻る', root_path %>

app/views/events/edit.html.erb
<% now = Time.zone.now %>

<div class="page-header">
  <h1>イベント情報編集</h1>
</div>

<%= form_for(@event, class: 'form-horizontal', role: 'form') do |f| %>

  <% if @event.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :place %>
    <%= f.text_field :place, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.file_field :event_image %>
  </div>
  <% if @event.event_image? %>
    <div class="checkbox">
      <label>
        <%= f.check_box :remove_event_image %>
        画像を削除する
      </label>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :start_time %>
    <div>
      <%= f.datetime_select :start_time,
        start_year: now.year,
        end_year: now.year + 1
      %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end_time %>
    <div>
      <%= f.datetime_select :end_time,
        start_year: now.year,
        end_year: now.year + 1
      %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>

  <%= f.submit '更新', class: 'btn btn-default', data: { disable_with: '更新中...' } %>
<% end %>

app/views/events/new.html.erb
<% now = Time.zone.now %>

<div class="page-header">
  <h1>イベント作成</h1>
</div>

<%= form_for(@event, class: 'form-horizontal', role: 'form') do |f| %>

  <% if @event.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :place %>
    <%= f.text_field :place, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.file_field :event_image %>
    <%= f.hidden_field :event_image_cache %>
  </div>
  <div class="form-group">
    <%= f.label :start_time %>
    <div>
      <%= f.datetime_select :start_time,
        start_year: now.year,
        end_year: now.year + 1
      %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end_time %>
    <div>
      <%= f.datetime_select :end_time,
        start_year: now.year,
        end_year: now.year + 1
      %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>

  <%= f.submit '作成', class: 'btn btn-default', data: { disable_with: '作成中...' } %>
<% end %>

app/views/events/show.html.erb
<div class="page-header">
  <h1><%= @event.name %></h1>
</div>

<div class="row">

  <!-- Event details -->
  <div class="col-md-8">
    <% if @event.event_image? %>
      <div class="thumbnail">
        <%= image_tag @event.event_image.url %>
      </div>
    <% end %>

    <div class="panel panel-default">
      <div class="panel-heading">
        主催者
      </div>
      <div class="panel-body">
        <% if @event.owner %>
          <%= link_to url_for_twitter(@event.owner) do %>
            <%= image_tag @event.owner.image_url %>
            <%= "@#{@event.owner.nickname}" %>
          <% end %>
        <% else %>
          退会したユーザです
        <% end %>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        開催時間
      </div>
      <div class="panel-body">
        <%= format_datetime(@event.start_time) %>
        <span>-</span>
        <%= format_datetime(@event.end_time) %>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        開催場所
      </div>
      <div class="panel-body">
        <%= @event.place %>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        イベント内容
      </div>
      <div class="panel-body">
        <%= @event.content %>
      </div>
    </div>
  </div>

  <!-- Actions -->
  <div class="col-md-4">
    <% if @event.created_by?(current_user) %>
      <%= link_to 'イベントを編集する', edit_event_path(@event),
        class: 'btn btn-info btn-lg btn-block'
      %>
      <%= link_to 'イベントを削除する', event_path(@event),
        method: :delete,
        class: 'btn btn-danger btn-lg btn-block',
        data: { confirm: '本当に削除しますか?' }
      %>
    <% end %>
    <% if logged_in? %>
      <% if @my_ticket %>
        <%= link_to '参加をキャンセルする',
          event_ticket_path(@event, @my_ticket),
          method: :delete,
          class: 'btn btn-warning btn-lg btn-block',
          data: { confirm: '本当にキャンセルしますか?' }
        %>
      <% else %>
        <button
          class="btn btn-primary btn-lg btn-block"
          data-toggle="modal"
          data-target="#ticket-modal"
          >
          イベントに参加する
        </button>
      <% end %>
    <% else %>
      <%= link_to 'イベントに参加する', new_event_ticket_path(@event),
        class: 'btn btn-primary btn-lg btn-block'
      %>
    <% end %>
    <hr>

    <!-- Participants -->
    <div class="panel panel-default">
      <div class="panel-heading">
        <% if @tickets.any? %>
          参加者
        <% else %>
          参加者はまだいません
        <% end %>
      </div>
      <div class="panel-body">
        <ul class="list-unstyled">
          <% @tickets.each do |ticket| %>
            <li>
              <% if ticket.user %>
                <%= link_to url_for_twitter(ticket.user) do %>
                  <%= image_tag ticket.user.image_url, width: 20, height: 20 %>
                  <%= "@#{ticket.user.nickname}" %>
                <% end %>
                <%= ticket.comment %>
              <% else %>
                退会したユーザです
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <!-- Modal dialog of the event register form -->
  <div id="ticket-modal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h4>参加コメント</h4>
        </div>
        <%= form_for @new_ticket,
          url: event_tickets_path(@event),
          role: 'form',
          remote: true do |f|
        %>
          <div class="modal-body">
              <%= f.text_field :comment, class: 'form-control' %>
          </div>
          <div class="modal-footer">
            <button class="btn btn-default" data-dismiss="modal">キャンセル</button>
            <%= f.button '送信',
              class: 'btn btn-primary',
              data: { disable_with: '送信中...' }
            %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AwesomeEvents</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <!-- Common Header -->
  <header class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button
          class="navbar-toggle"
          data-toggle="collapse"
          data-target="#navbar-menu"
        >
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'AwesomeEvents', root_path, class: 'navbar-brand' %>
      </div>
      <div id="navbar-menu" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to 'イベントを作る', new_event_path %>
          </li>
          <% if logged_in? %>
            <li><%= link_to '退会する', user_retire_path(current_user) %></li>
            <li><%= link_to 'ログアウト', '/logout' %></li>
          <% else %>
            <li><%= link_to 'Twitterでログイン', '/auth/twitter' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </header>

  <!-- Main container -->
  <div class="container">

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/users/retire.html.erb
<div class="page-header">
  <h1>退会の確認</h1>
</div>

<% if current_user.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% current_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container">
  <p>退会した場合、ユーザに関するデータが全て削除されます。</p>
  <p>ただし、以下の場合は退会できません。</p>
  <ul>
    <li>公開中の未終了イベントがある場合</li>
    <li>未終了の参加イベントがある場合</li>
  </ul>
  <hr>
  <%= link_to '退会する', user_path(current_user),
    method: :delete,
    class: 'btn btn-danger'
  %>
</div>

app/views/welcome/index.html.erb
<div class="page-header">
  <h1>イベント一覧</h1>
</div>

<div class="list-group">
  <% @events.each do |event| %>
    <%= link_to(event, class: 'list-group-item') do %>
      <h4 class="list-group-item-heading">
        <%= event.name %>
      </h4>
      <p class="list-group-item-text">
        <%= format_datetime(event.start_time) %>
        <span>-</span>
        <%= format_datetime(event.end_time) %>
      </p>
    <% end %>
  <% end %>
  <%= paginate @events %>
</div>